global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application (when deployed)
  - job_name: 'recommendation-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'

  # Qdrant metrics (if available)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
